name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: prettier
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write **/*.{js,md}
      - name: Start MongoDB v${{ matrix.mongodb-version }}
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: test
        run: npm test
